#端口号
server:
  port: 8081


#数据源的配置 告诉java程序,我们的数据库地址以及一些必要的信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #数据库id自增
  configuration:
    map-underscore-to-camel-case: false  # 开启驼峰命名
    auto-mapping-behavior: full # 自动映射任何复杂结果
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
